### ISSUE TITLE
bluepy.btle.BTLEGattError when trying to pare device?

### ISSUE THREAD

**Issue by neuronflow** [HBDK/Eco2-Tools#12]
I am trying to pair a device and receive the following error, on a side note should the scan tool list multiple device ids? If not probably my raspis bluetooth module is not strong enough?
```
Proceeding with '00:04:2f:79:44:cf' as ID
Press the clock button on the thermostat when you get the following message:
'libetrv.device:connect:54 - Trying connect to 00:04:2f:79:44:cf'
Starting
2021-01-23 16:54:56.180 | DEBUG    | libetrv.device:connect:54 - Trying connect to 00:04:2f:79:44:cf
2021-01-23 16:55:05.955 | DEBUG    | libetrv.device:send_pin:87 - Write PIN to 00:04:2f:79:44:cf
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/libetrv/cli.py", line 79, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/libetrv/cli.py", line 47, in retrieve_key
    print("Secret Key:", self._device.secret_key)
  File "/usr/local/lib/python3.8/site-packages/libetrv/properties.py", line 22, in __get__
    return self.get_data_object(device).retrieve()
  File "/usr/local/lib/python3.8/site-packages/libetrv/properties.py", line 59, in retrieve
    self.read()
  File "/usr/local/lib/python3.8/site-packages/libetrv/properties.py", line 91, in read
    data = etrv_read_data(self.device, handler, send_pin, use_encoding)
  File "/usr/local/lib/python3.8/site-packages/libetrv/utils.py", line 20, in etrv_read_data
    data = device.ble_device.readCharacteristic(handler)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 14, error: Request attribute has encountered an unlikely error)
In 5 seconds this script will try to retrieve a secure key from eTRV device. Don't forget to save it for later. Before that be sure that device is in pairing mode. You can achieve that by pressing button on device
stopping
```

**Comment by HBDK** [comment]
The scan tool should list all devices within range.
are you sure you are following the instructions and pressing the pair button at the right time?

anyway if the scan tool runs without issues than i'm pretty certain this is either a user error, a issue with your thermostat or an issue in the underlying software. so it's not really a relevant issue for this repository (this repo only packages the software).

so i'll take the liberty to close this issue.
