### ISSUE TITLE
Stopped working after HA Core 2022.8.x update

### ISSUE THREAD

**Issue by Plampi64** [HBDK/Eco2-Tools#20]
<< Made new Issue to etrv2mqtt (https://github.com/keton/etrv2mqtt/issues/16) so followup there !! >>

Seems that new HA Core 2022.8.x with Bluetooth functionality somehow broke this. etrv_scan log shows:

Start scanning
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/libetrv/cli.py", line 79, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/libetrv/cli.py", line 22, in scan
    for device in eTRVDevice.scan(timeout):
  File "/usr/local/lib/python3.9/site-packages/libetrv/device.py", line 38, in scan
    devices = btle.Scanner().scan(timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 800, in start
    self._mgmtCmd(self._cmd())
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scan'
Detected eTRV devices:
Done scanning

**Comment by HBDK** [comment]
I'm not experiencing the same behavior and there is no steps to reproduce so i will just close this.
