### ISSUE TITLE
Do these work via the ESPHome BLE proxy?

### ISSUE THREAD

**Issue by Aephir** [HBDK/Eco2-Tools#23]
I am running my eTRVs far away from my HA, so I was trying with the ESPHome bluetooth proxy nearby.

It doesn't seem to work. The keytool never finds anything when I press the button (I already had the MAC), and the etrv scan just shows:

```
Start scanning
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/libetrv/cli.py", line 80, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/libetrv/cli.py", line 22, in scan
    for device, key in eTRVDevice.scan(timeout):
  File "/usr/local/lib/python3.9/site-packages/libetrv/device.py", line 41, in scan
    devices = btle.Scanner().scan(1)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
Detected eTRV devices:
Done scanning
```

in the logs..

Is this something that can work and if so, is it something that has to be addressed on the ESPHome side, or here?

**Comment by HBDK** [comment]
This have nothing to do with Home assistant or Esp home. having esphome proxies won't do anything here.

(that aside the proxy is afik currently limited to reading values from ble devices it won't establish active connections needed to interface with the thermostats)

the tools currently doesn't work on hassos for some reason, i can't reproduce it on my workstation so i'm currently not sure how to solve it, but it will work fine on other machines so just use something else to grap the keys for now.

**Comment by JR-bva** [comment]
Hi.
We've encountered the same error and assume the problem is the update to Python 3.10 and the associated non-functionality of the bluepy. At least in new installations.
https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes
Is there any chance that the code will be rewritten based on this information?
Thanks.
