### ISSUE TITLE
key scan failed

### ISSUE THREAD

**Issue by kec2** [HBDK/Eco2-Tools#28]
So I pressed the clock button and this was the response.

Press the clock button on the thermostat when you get the following message:
'libetrv.device:connect:54 - Trying connect to 00:04:2f:0f:13:1f'
Starting
2024-01-07 11:52:35.672 | DEBUG    | libetrv.device:connect:81 - Trying connect to 00:04:2f:0f:13:1f
2024-01-07 11:52:43.430 | DEBUG    | libetrv.device:send_pin:114 - Write PIN to 00:04:2f:0f:13:1f
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/libetrv/cli.py", line 80, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/libetrv/cli.py", line 48, in retrieve_key
    print("Secret Key:", self._device.secret_key)
  File "/usr/local/lib/python3.9/site-packages/libetrv/properties.py", line 22, in __get__
    return self.get_data_object(device).retrieve()
  File "/usr/local/lib/python3.9/site-packages/libetrv/properties.py", line 59, in retrieve
    self.read()
  File "/usr/local/lib/python3.9/site-packages/libetrv/properties.py", line 91, in read
    data = etrv_read_data(self.device, handler, send_pin, use_encoding)
  File "/usr/local/lib/python3.9/site-packages/libetrv/utils.py", line 20, in etrv_read_data
    data = device.ble_device.readCharacteristic(handler)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 14, error: Request attribute has encountered an unlikely error)
In 5 seconds this script will try to retrieve a secure key from eTRV device. Don't forget to save it for later. Before that be sure that device is in pairing mode. You can achieve that by pressing button on device
stopping

**Comment by kec2** [comment]
Today it works just fine.
