### ISSUE TITLE
etrv-scan no working

### ISSUE THREAD

**Issue by djmalin** [HBDK/Eco2-Tools#7]
Hello i have this problem:
Operating System HassOS 4.17 
Supervisor: 2020.11.0

Start scanning
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/libetrv/cli.py", line 79, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/libetrv/cli.py", line 22, in scan
    for device in eTRVDevice.scan(timeout):
  File "/usr/local/lib/python3.8/site-packages/libetrv/device.py", line 38, in scan
    devices = btle.Scanner().scan(timeout)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 854, in scan
    self.stop()
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 803, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 11, error: Rejected)
Detected eTRV devices:
Done scanning

when I find the address of the head myself, I can't pull out the key

Proceeding with '00:04:2f:61:24:1e' as ID
Press the clock button on the thermostat when you get the:
'libetrv.device:connect:54 - Trying connect to 00:04:2f:61:24:1e'
messeage
Starting
2020-11-27 12:17:14.641 | DEBUG    | libetrv.device:connect:54 - Trying connect to 00:04:2f:61:24:1e
2020-11-27 12:17:14.655 | ERROR    | libetrv.device:connect:68 - Unable connect to 00:04:2f:61:24:1e. Retrying in 100ms
2020-11-27 12:17:14.768 | ERROR    | libetrv.device:connect:68 - Unable connect to 00:04:2f:61:24:1e. Retrying in 100ms

**Comment by HBDK** [comment]
i can't reproduce the first part.

and about the key tool again i can't reproduce, but make sure the thermostat is close to the hassio machine when you try to pair and make sure to press the button when it's ready.

i can't really do anything about this with the info you have provided.

**Comment by Czarnykowal** [comment]
I have got the same error because the thermostat was in M mode. It has to be installed and then as per instruction press clock button when you get: "Press the clock button on the thermostat when you get the following message:" and it works :)
